language: node_js
node_js: 12
before_install:
- npm run audit:whitelisted
install:
- npm ci
script:
- make validate-no-uncommitted-package-lock-changes
- npm run i18n_extract
- npm run lint
- npm run test
- npm run build
